### ISSUE TITLE
Usage as non privileged user

### ISSUE THREAD

**Issue by alvagante** [sbitio/puppet-pipx#1]
How the pipx provider is expected to be used as a normal non privileged user?

**Comment by jonhattan** [comment]
The provider by default works system-wide (parameter `$global = true` in main class), for per-user usage just disable this funcionality, for example with this hiera snippet:

```yaml
puppet_pipx::global: false
```

I case you want both global and per-user usage I don't think the module supports this at present. We could do it, just need to think about a feasible implementation.

**Comment by alvagante** [comment]
Perfect, thanks, I should have checked better the code.
