### ISSUE TITLE
Question: Compatibility with `pipx --global`

### ISSUE THREAD

**Issue by crown-bdee** [sbitio/puppet-pipx#3]
As of the fairly recent [1.5.0 release of `pipx`](https://github.com/pypa/pipx/releases/tag/1.5.0) the `--global` option has been introduced. Is the script installation method used by this Puppet module compatible with that implementation?
This module obviously preceded that support by quite some time, so I fully understand if they aren't.

**Comment by crown-bdee** [comment]
Reading a bit further, it looks like it probably is compatible, since the same `/opt/pipx` HOME location is used: https://pipx.pypa.io/stable/installation/#global-installation

**Comment by jonhattan** [comment]
Great news! Thanks for the investigation!

In a future when 1.5 is generally available in distros I'll remove pipx-global. Thanks!
